name: Update Proton CachyOS

on:
  schedule:
    - cron: "0 0 * * *"  # Daily at midnight
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Check for new version
        id: check_version
        run: |
          # Get current version from default.nix
          CURRENT_VERSION=$(grep 'version = ' default.nix | sed 's/.*version = "\(.*\)";/\1/')
          echo "Current version: $CURRENT_VERSION"
          
          # Fetch latest version from CachyOS repo
          LISTING=$(curl -s "https://mirror.cachyos.org/repo/x86_64_v3/cachyos-v3/")
          
          # Extract the latest proton-cachyos package
          LATEST_FILENAME=$(echo "$LISTING" | \
            grep -o 'href="proton-cachyos-[^"]*\.pkg\.tar\.zst"' | \
            grep -o 'proton-cachyos-[^"]*\.pkg\.tar\.zst' | \
            sort -V | \
            tail -n1)
          
          if [ -z "$LATEST_FILENAME" ]; then
            echo "Error: Could not find proton-cachyos package"
            exit 1
          fi
          
          # Extract version from filename
          # proton-cachyos-1%3A10.0.20250714-1-x86_64_v3.pkg.tar.zst
          LATEST_VERSION=$(echo "$LATEST_FILENAME" | \
            sed 's/proton-cachyos-\(.*\)-x86_64_v3\.pkg\.tar\.zst/\1/' | \
            sed 's/%3A/:/g')
          
          echo "Latest version: $LATEST_VERSION"
          echo "Latest filename: $LATEST_FILENAME"
          
          # Check if version is different
          if [ "$CURRENT_VERSION" != "$LATEST_VERSION" ]; then
            echo "New version available!"
            echo "current_version=$CURRENT_VERSION" >> $GITHUB_OUTPUT
            echo "latest_version=$LATEST_VERSION" >> $GITHUB_OUTPUT
            echo "latest_filename=$LATEST_FILENAME" >> $GITHUB_OUTPUT
            echo "update_needed=true" >> $GITHUB_OUTPUT
          else
            echo "No update needed"
            echo "update_needed=false" >> $GITHUB_OUTPUT
          fi

      - name: Calculate new hash
        if: steps.check_version.outputs.update_needed == 'true'
        id: calc_hash
        run: |
          URL="https://mirror.cachyos.org/repo/x86_64_v3/cachyos-v3/${{ steps.check_version.outputs.latest_filename }}"
          echo "Calculating hash for: $URL"
          
          HASH=$(nix-prefetch-url --type sha256 "$URL")
          echo "Hash: $HASH"
          echo "hash=$HASH" >> $GITHUB_OUTPUT

      - name: Update default.nix
        if: steps.check_version.outputs.update_needed == 'true'
        run: |
          # Update version
          sed -i 's/version = ".*";/version = "${{ steps.check_version.outputs.latest_version }}";/' default.nix
          
          # Update URL
          sed -i 's|url = "https://mirror.cachyos.org/repo/x86_64_v3/cachyos-v3/.*";|url = "https://mirror.cachyos.org/repo/x86_64_v3/cachyos-v3/${{ steps.check_version.outputs.latest_filename }}";|' default.nix
          
          # Update hash
          sed -i 's/sha256 = ".*";/sha256 = "${{ steps.calc_hash.outputs.hash }}";/' default.nix

      - name: Create Pull Request
        if: steps.check_version.outputs.update_needed == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Update proton-cachyos to ${{ steps.check_version.outputs.latest_version }}"
          title: "Update proton-cachyos to ${{ steps.check_version.outputs.latest_version }}"
          body: |
            Automated update of proton-cachyos from ${{ steps.check_version.outputs.current_version }} to ${{ steps.check_version.outputs.latest_version }}.
            
            - **Previous version**: ${{ steps.check_version.outputs.current_version }}
            - **New version**: ${{ steps.check_version.outputs.latest_version }}
            - **Package**: ${{ steps.check_version.outputs.latest_filename }}
            
            This PR was automatically generated by the update workflow.
          branch: update-proton-cachyos
          delete-branch: true